name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  plugin_test:
    name: asdf plugin test
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: asdf plugin test
        uses: asdf-vm/actions/plugin-test@v4
        with:
          command: terramaid version
          version: 2.6.2
          gitref: ${{ github.head_ref || github.ref_name }}
